'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*")>  _
        Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Agregar(ByVal codAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*")>  _
        Function AgregarAsync(ByVal codAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminarAlumno(ByVal codAlumno As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarAlumno", ReplyAction:="*")>  _
        Function EliminarAlumnoAsync(ByVal codAlumno As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarAlumno(ByVal CodAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarAlumno", ReplyAction:="*")>  _
        Function ActualizarAlumnoAsync(ByVal CodAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SearchEscuela", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SearchEscuela(ByVal CodAlumno As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SearchEscuela", ReplyAction:="*")>  _
        Function SearchEscuelaAsync(ByVal CodAlumno As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Listar() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Listar
            Return MyBase.Channel.Listar
        End Function
        
        Public Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.ListarAsync
            Return MyBase.Channel.ListarAsync
        End Function
        
        Public Function Agregar(ByVal codAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As Boolean Implements ServiceReference1.WebService1Soap.Agregar
            Return MyBase.Channel.Agregar(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela)
        End Function
        
        Public Function AgregarAsync(ByVal codAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.AgregarAsync
            Return MyBase.Channel.AgregarAsync(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela)
        End Function
        
        Public Function EliminarAlumno(ByVal codAlumno As String) As Boolean Implements ServiceReference1.WebService1Soap.EliminarAlumno
            Return MyBase.Channel.EliminarAlumno(codAlumno)
        End Function
        
        Public Function EliminarAlumnoAsync(ByVal codAlumno As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.EliminarAlumnoAsync
            Return MyBase.Channel.EliminarAlumnoAsync(codAlumno)
        End Function
        
        Public Function ActualizarAlumno(ByVal CodAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As Boolean Implements ServiceReference1.WebService1Soap.ActualizarAlumno
            Return MyBase.Channel.ActualizarAlumno(CodAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela)
        End Function
        
        Public Function ActualizarAlumnoAsync(ByVal CodAlumno As String, ByVal Apellidos As String, ByVal Nombres As String, ByVal LugarNac As String, ByVal FechaNac As Date, ByVal CodEscuela As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.ActualizarAlumnoAsync
            Return MyBase.Channel.ActualizarAlumnoAsync(CodAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela)
        End Function
        
        Public Function SearchEscuela(ByVal CodAlumno As String) As Boolean Implements ServiceReference1.WebService1Soap.SearchEscuela
            Return MyBase.Channel.SearchEscuela(CodAlumno)
        End Function
        
        Public Function SearchEscuelaAsync(ByVal CodAlumno As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.WebService1Soap.SearchEscuelaAsync
            Return MyBase.Channel.SearchEscuelaAsync(CodAlumno)
        End Function
    End Class
End Namespace
